import clientPromise from "@/lib/mongoClient";
import {MongoDBAdapter} from "@auth/mongodb-adapter";
import {AuthOptions} from "next-auth";
import GoogleProvider from "next-auth/providers/google";

/**
 * Options for authentication in the application.
 *
 * This object is used by Next.js to configure the authentication providers.
 */
export const authOptions:AuthOptions = {
  // The secret used to sign the tokens generated by the authentication adapter.
  secret: process.env.AUTH_SECRET,
  // An array of provider objects to enable for the authentication flow.
  providers: [
    // Configure the Google provider.
    GoogleProvider({
      // The client ID obtained from the Google Cloud Console.
      clientId: process.env.GOOGLE_CLIENT_ID as string,
      // The client secret obtained from the Google Cloud Console.
      clientSecret: process.env.GOOGLE_CLIENT_SECRET as string,
    }),
  ],
  // @ts-ignore
  adapter: MongoDBAdapter(clientPromise),
};
